
services:
    naoned.oaipmh.ruler:
        class: Naoned\OaiPmhServerBundle\OaiPmh\OaiPmhRuler
        calls:
            - [ setCountPerLoad, [ '%naoned.oaipmh_server.count_per_load%' ] ]

    naoned.oaipmh.twig.record_extension:
        class: Naoned\OaiPmhServerBundle\Twig\RecordExtension
        calls:
            - [ setDataProvider, [ "@naoned.oaipmh.data_provider" ] ]
        tags:
            - { name: twig.extension }

    naoned.oaipmh.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["@=service('kernel').getCacheDir()"]
